backend:
  name: git-gateway
  repo: scottmo223/bellevue

publish_mode: editorial_workflow
media_folder: /content/assets

collections:
  - name: "home"
    label: "Home Page"
    files: 
      - label: "About Section"
        name: "about"
        file: "content/blog/aboutme.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Body", widget: "markdown" }